## numpy

- arrays
- accessing elements
- making calculations on arrays
- boolean indexing 



In [1]:
import numpy as np

In [27]:
np.random.randint(1, 10, 2)

array([5, 5])

In [11]:
## Create a 10 x 10 2d array of random integers between 1 and 10

arr1 = np.random.randint(1, 11, 100).reshape((10, 10))
arr1

array([[ 9,  4,  7,  2,  2,  3,  9,  2,  4,  1],
       [ 3,  1, 10,  9,  5,  4,  8,  5, 10,  2],
       [ 2,  3,  3,  4,  3,  5,  1,  1,  1,  8],
       [ 5,  5,  5,  7,  2,  3,  6,  4,  1,  8],
       [ 7,  4,  9,  4,  3,  2,  4,  2,  6,  1],
       [10,  5,  1,  7,  7, 10,  9,  4, 10,  3],
       [ 4,  3,  9,  7, 10,  8,  6,  5,  5,  1],
       [ 9,  2,  9,  2,  8,  3,  6, 10, 10, 10],
       [ 9,  2,  1, 10, 10,  2,  6,  3,  8,  1],
       [ 2,  4,  4,  1,  4,  3,  6,  2,  4,  8]])

In [4]:
## single element

arr1[2, 2]

2

In [5]:
arr1[2:7,3:6]

array([[ 2, 10,  2],
       [ 8,  7,  8],
       [ 2,  6,  2],
       [ 2,  4,  4],
       [ 9,  7,  6]])

In [ ]:
## extract all the even numbers out from the array

In [7]:
arr1[arr1 % 2 == 0]

array([ 8,  6,  2, 10,  6,  2, 10,  6,  2,  2, 10,  2,  6,  8, 10,  8,  8,
        8, 10, 10,  6,  2,  2,  6,  2,  6,  6,  6,  8,  4,  6,  2,  4,  4,
        4,  6, 10,  8,  6,  2,  2,  4, 10,  8,  4, 10,  8,  2,  8,  4, 10,
        6, 10, 10,  8])

In [10]:
arr1[(arr1 % 2 == 0) & (arr1 % 5 == 0)]

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [9]:
(arr1 % 2 == 0) & (arr1 % 5 == 0)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True, False, False, False, False, False, False,
        False],
       [ True, False, False, False,  True, False, False, False, False,
        False],
       [False,  True, False, False, False, False,  True,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False,  True, False, False, False, False, False,  True,  True,
        False]])

`.transpose()`     `.T`

In [30]:
arr1

array([[ 9,  4,  7,  2,  2,  3,  9,  2,  4,  1],
       [ 3,  1, 10,  9,  5,  4,  8,  5, 10,  2],
       [ 2,  3,  3,  4,  3,  5,  1,  1,  1,  8],
       [ 5,  5,  5,  7,  2,  3,  6,  4,  1,  8],
       [ 7,  4,  9,  4,  3,  2,  4,  2,  6,  1],
       [10,  5,  1,  7,  7, 10,  9,  4, 10,  3],
       [ 4,  3,  9,  7, 10,  8,  6,  5,  5,  1],
       [ 9,  2,  9,  2,  8,  3,  6, 10, 10, 10],
       [ 9,  2,  1, 10, 10,  2,  6,  3,  8,  1],
       [ 2,  4,  4,  1,  4,  3,  6,  2,  4,  8]])

In [29]:
arr1.T

array([[ 9,  3,  2,  5,  7, 10,  4,  9,  9,  2],
       [ 4,  1,  3,  5,  4,  5,  3,  2,  2,  4],
       [ 7, 10,  3,  5,  9,  1,  9,  9,  1,  4],
       [ 2,  9,  4,  7,  4,  7,  7,  2, 10,  1],
       [ 2,  5,  3,  2,  3,  7, 10,  8, 10,  4],
       [ 3,  4,  5,  3,  2, 10,  8,  3,  2,  3],
       [ 9,  8,  1,  6,  4,  9,  6,  6,  6,  6],
       [ 2,  5,  1,  4,  2,  4,  5, 10,  3,  2],
       [ 4, 10,  1,  1,  6, 10,  5, 10,  8,  4],
       [ 1,  2,  8,  8,  1,  3,  1, 10,  1,  8]])

In [32]:
arr1 = arr1.transpose()

## pandas - panel data analysis

pandas is an extremely important library to know for data analysts and scientists as it is the industry standard package used to work with structured data in python. Initially created with the intention to handle **panel data**, pandas today is used to work with any kind of **structured data** in python.

Panel data - a kind of time series data

structured data - tabular data; data organized in rows and columns

built on top of numpy

Pandas provides 2 more datastructures

1. `pd.Series` - 1D homogeneous datastructure built on top of numpy arrays

2. `pd.DataFrame` - 2D heterogeneous datasturcture

DataFrame is like a table. Series is like a single column or a single row.

In [34]:
import pandas as pd  ## import pandas

In [36]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bda

## `pd.Series`

`pd.Series()`

In [37]:
## 1. creation

s1 = pd.Series([1, 2, 3, 4, 5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [38]:
s2 = pd.Series(np.arange(0, 10, 2))
s2

0    0
1    2
2    4
3    6
4    8
dtype: int32

In [39]:
## create random salaries

s3 = pd.Series(np.random.randint(20000, 100000, 100))
s3

0     79237
1     22466
2     41592
3     72400
4     71354
      ...  
95    27657
96    92332
97    49701
98    88372
99    78425
Length: 100, dtype: int32

## Accessing elements

pd.Series supports 2 kinds of indexes

1. Default index: automatically will provide a default index starting from 0 going till end - 1.

2. User defined index: also supports a user defined index which can be either numeric or string type.



to avoid all the confusion regarding which index (used defined or default) will be used to access elements
with simple `[ ]`

pandas introduced 2 very important attributes

`.loc[]`

this works on the user defined index

when slicing, the final value is inclusive

supports boolean indexing

`.iloc[]`

this works on the default index (integer location)

when slicing, the final value is exclusive

.iloc doesn't support boolean indexing

In [42]:
s4 = pd.Series([100, 101, 110, 120], index=['Jan', 'Feb', 'March', 'April'])
s4

Jan      100
Feb      101
March    110
April    120
dtype: int64

In [43]:
## products data


s5 = pd.Series(['Apple iphone', 'Samsung phone1', 'Nokia phone1'], index=[1001, 1002, 1003])

In [44]:
s5

1001      Apple iphone
1002    Samsung phone1
1003      Nokia phone1
dtype: object

In [45]:
## accessing elements

s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [46]:
s4

Jan      100
Feb      101
March    110
April    120
dtype: int64

In [47]:
s6 = pd.Series([1, 2, 3, 4, 5], index=range(1, 6))
s6

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [48]:
## s1

In [50]:
s1[0]

1

In [52]:
s1[1:4]

1    2
2    3
3    4
dtype: int64

In [56]:
s6[1]  ## works on the user defined index

1

In [59]:
s6[1:4]  ## slicing now it used default index

2    2
3    3
4    4
dtype: int64

In [60]:
s6

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [61]:
s6[0:4]  ## last element got included

1    1
2    2
3    3
4    4
dtype: int64

In [63]:
s4['Jan']

100

In [64]:
s4[0]

100

In [68]:
## access data from Jan till March

s4[0:3]  ## slicing

Jan      100
Feb      101
March    110
dtype: int64

In [70]:
s4['Jan': 'March']  ## also supported

Jan      100
Feb      101
March    110
dtype: int64

In [73]:
## .loc and .iloc

## whenever user defined index is not provided, the user defined index defaults to the default index

In [72]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [74]:
s1[0]

1

In [75]:
s1.loc[0]

1

In [76]:
s1.iloc[0]

1

In [77]:
s4

Jan      100
Feb      101
March    110
April    120
dtype: int64

In [80]:
## Access the data for Feb

s4.loc['Feb']

101

In [83]:
## Access teh data for Feb using .iloc

s4.iloc[1]

101

In [84]:
## slicing

## get the data from Jan till March

## .loc


In [86]:
s4.loc['Jan': 'March']  ## it goes till the last; exclusive rule doesn't apply

Jan      100
Feb      101
March    110
dtype: int64

In [89]:
s4.iloc[0:3]   ## .iloc is exclusive of the last value

Jan      100
Feb      101
March    110
dtype: int64

In [90]:
## boolean indexing

s4

Jan      100
Feb      101
March    110
April    120
dtype: int64

In [92]:
## extract the values where sales is greater than $105

s4[s4 > 105]  ## boolean index

March    110
April    120
dtype: int64

In [93]:
s4 > 105

Jan      False
Feb      False
March     True
April     True
dtype: bool

In [94]:
s4.loc[s4 > 105]

March    110
April    120
dtype: int64

In [95]:
s4.iloc[s4>105]

ValueError: iLocation based boolean indexing cannot use an indexable as a mask

In [96]:
## making calculations

s4

Jan      100
Feb      101
March    110
April    120
dtype: int64

In [97]:
##  compute the profit given that the profit margin is 0.1

## profit = sales * profit_margin

In [98]:
s4 * 0.1

Jan      10.0
Feb      10.1
March    11.0
April    12.0
dtype: float64

In [99]:
s4 + 10

Jan      110
Feb      111
March    120
April    130
dtype: int64

In [100]:
s4 / 10

Jan      10.0
Feb      10.1
March    11.0
April    12.0
dtype: float64

In [101]:
s4 > 10

Jan      True
Feb      True
March    True
April    True
dtype: bool

In [102]:
## For Jan and Feb, the profit margin was 0.1
## for March, aprile, the profit margin 0.2

In [120]:
s4.loc["Jan": 'Feb'] = s4.loc["Jan": 'Feb'] * 0.1

In [119]:
s4.loc['March': 'April'] = s4.loc['March': 'April'] * 0.2

In [121]:
s4

Jan      11.0
Feb      10.1
March    22.0
April    24.0
dtype: float64

In [108]:
## updating a series

In [111]:
s4[0] = 110

In [112]:
s4

Jan      110
Feb      101
March    110
April    120
dtype: int64

In [114]:
s4.loc["Jan"] = 100

In [115]:
s4

Jan      100
Feb      101
March    110
April    120
dtype: int64

In [117]:
s4.iloc[0] = 110

In [118]:
s4

Jan      110
Feb      101
March    110
April    120
dtype: int64

In [122]:
s4.loc["Jan": 'Feb'] *= 0.1

In [123]:
s4

Jan       1.10
Feb       1.01
March    22.00
April    24.00
dtype: float64

## pd.DataFrame()

`pd.DataFrame()`


In [124]:
## pass a dictionary

dict1 = {'ProductId': [1001, 1002, 1003], 
         'Names': ['Product1', 'Prod2', 'Prod3'], 
         'Cost': [10.2, 11, 12]}

In [125]:
pd.DataFrame(dict1)

ProductId     Names  Cost
0       1001  Product1  10.2
1       1002     Prod2  11.0
2       1003     Prod3  12.0

In [127]:
## importing data from the outside and then creating DataFrames


In [128]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bda

`pd.read_csv()`

In [130]:
data1 = pd.read_csv(r'D:\Data\datasets\LoansData.csv')
data1

LoanID  Amount.Requested  Amount.Funded.By.Investors Interest.Rate  \
0          1           20000.0                    20000.00         8.90%   
1          2           19200.0                    19200.00        12.12%   
2          3           35000.0                    35000.00        21.98%   
3          4           10000.0                     9975.00         9.99%   
4          5           12000.0                    12000.00        11.71%   
...      ...               ...                         ...           ...   
2495    2496           30000.0                    29950.00        16.77%   
2496    2497           16000.0                    16000.00        14.09%   
2497    2498           10000.0                    10000.00        13.99%   
2498    2499            6000.0                     6000.00        12.42%   
2499    2500            9000.0                     5242.75        13.79%   

     Loan.Length        Loan.Purpose Debt.To.Income.Ratio State  \
0      36 months  debt_consolidation               14.90%    SC   
1      36 months  debt_consolidation               28.36%    TX   
2      60 months  debt_consolidation               23.81%    CA   
3      36 months  debt_consolidation               14.30%    KS   
4      36 months         credit_card               18.78%    NJ   
...          ...                 ...                  ...   ...   
2495   60 months  debt_consolidation               19.23%    NY   
2496   60 months    home_improvement               21.54%    MD   
2497   36 months  debt_consolidation                4.89%    PA   
2498   36 months      major_purchase               16.66%    NJ   
2499   36 months  debt_consolidation                6.76%    NY   

     Home.Ownership  Monthly.Income FICO.Range  Open.CREDIT.Lines  \
0          MORTGAGE         6541.67    735-739               14.0   
1          MORTGAGE         4583.33    715-719               12.0   
2          MORTGAGE        11500.00    690-694               14.0   
3          MORTGAGE         3833.33    695-699               10.0   
4              RENT         3195.00    695-699               11.0   
...             ...             ...        ...                ...   
2495       MORTGAGE         9250.00    705-709               15.0   
2496            OWN         8903.25    740-744               18.0   
2497       MORTGAGE         2166.67    680-684                4.0   
2498           RENT         3500.00    675-679                8.0   
2499           RENT         3875.00    670-674                7.0   

      Revolving.CREDIT.Balance  Inquiries.in.the.Last.6.Months  \
0                      14272.0                             2.0   
1                      11140.0                             1.0   
2                      21977.0                             1.0   
3                       9346.0                             0.0   
4                      14469.0                             0.0   
...                        ...                             ...   
2495                   45880.0                             1.0   
2496                   18898.0                             1.0   
2497                    4544.0                             0.0   
2498                    7753.0                             0.0   
2499                    7589.0                             0.0   

     Employment.Length  
0             < 1 year  
1              2 years  
2              2 years  
3              5 years  
4              9 years  
...                ...  
2495           8 years  
2496         10+ years  
2497         10+ years  
2498           5 years  
2499         10+ years  

[2500 rows x 15 columns]

In [131]:
type(data1)

pandas.core.frame.DataFrame

In [132]:
## comma delimited

## tab delimited, semi-colon delimited

In [133]:
pd.read_csv?

In [136]:
data2 = pd.read_csv(r'D:/Data/datasets/bank-additional.csv', sep=';')
data2

age          job  marital          education default  housing     loan  \
0      30  blue-collar  married           basic.9y      no      yes       no   
1      39     services   single        high.school      no       no       no   
2      25     services  married        high.school      no      yes       no   
3      38     services  married           basic.9y      no  unknown  unknown   
4      47       admin.  married  university.degree      no      yes       no   
...   ...          ...      ...                ...     ...      ...      ...   
4114   30       admin.  married           basic.6y      no      yes      yes   
4115   39       admin.  married        high.school      no      yes       no   
4116   27      student   single        high.school      no       no       no   
4117   58       admin.  married        high.school      no       no       no   
4118   34   management   single        high.school      no      yes       no   

        contact month day_of_week  ...  campaign  pdays  previous  \
0      cellular   may         fri  ...         2    999         0   
1     telephone   may         fri  ...         4    999         0   
2     telephone   jun         wed  ...         1    999         0   
3     telephone   jun         fri  ...         3    999         0   
4      cellular   nov         mon  ...         1    999         0   
...         ...   ...         ...  ...       ...    ...       ...   
4114   cellular   jul         thu  ...         1    999         0   
4115  telephone   jul         fri  ...         1    999         0   
4116   cellular   may         mon  ...         2    999         1   
4117   cellular   aug         fri  ...         1    999         0   
4118   cellular   nov         wed  ...         1    999         0   

         poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0     nonexistent         -1.8          92.893          -46.2      1.313   
1     nonexistent          1.1          93.994          -36.4      4.855   
2     nonexistent          1.4          94.465          -41.8      4.962   
3     nonexistent          1.4          94.465          -41.8      4.959   
4     nonexistent         -0.1          93.200          -42.0      4.191   
...           ...          ...             ...            ...        ...   
4114  nonexistent          1.4          93.918          -42.7      4.958   
4115  nonexistent          1.4          93.918          -42.7      4.959   
4116      failure         -1.8          92.893          -46.2      1.354   
4117  nonexistent          1.4          93.444          -36.1      4.966   
4118  nonexistent         -0.1          93.200          -42.0      4.120   

      nr.employed   y  
0          5099.1  no  
1          5191.0  no  
2          5228.1  no  
3          5228.1  no  
4          5195.8  no  
...           ...  ..  
4114       5228.1  no  
4115       5228.1  no  
4116       5099.1  no  
4117       5228.1  no  
4118       5195.8  no  

[4119 rows x 21 columns]

In [138]:
## excel

data3 = pd.read_excel('d:/data/datasets/stock_price_data2.xlsx')
data3

Date        Open        High         Low       Close   Adj Close  \
0    1998-11-27    3.550000    3.550000    2.710000    3.400000    2.257744   
1    1998-11-30    3.250000    3.300000    3.100000    3.210000    2.131575   
2    1998-12-01    3.290000    3.460000    3.220000    3.390000    2.251104   
3    1998-12-02    3.360000    3.440000    3.320000    3.390000    2.251104   
4    1998-12-03    3.440000    3.490000    3.370000    3.390000    2.251104   
...         ...         ...         ...         ...         ...         ...   
6144 2023-06-19  983.849976  986.000000  961.000000  965.650024  965.650024   
6145 2023-06-20  965.950012  977.000000  958.549988  974.849976  974.849976   
6146 2023-06-21  978.299988  978.299988  963.150024  966.000000  966.000000   
6147 2023-06-22  962.200012  973.450012  958.700012  966.599976  966.599976   
6148 2023-06-23  960.000000  965.500000  954.549988  958.400024  958.400024   

        Volume  
0        21000  
1       132000  
2       123500  
3        75500  
4       102000  
...        ...  
6144  11025846  
6145   7596593  
6146   7805855  
6147  10135883  
6148   6188008  

[6149 rows x 7 columns]

In [141]:
data = pd.read_excel('d:/data/datasets/stock_price_data2.xlsx', sheet_name=None)

In [142]:
type(data)

dict

In [144]:
type(data['AXISBANK.NS'])

pandas.core.frame.DataFrame

In [146]:
data['AXISBANK.NS']

Date        Open        High         Low       Close   Adj Close  \
0    1998-11-27    3.550000    3.550000    2.710000    3.400000    2.257744   
1    1998-11-30    3.250000    3.300000    3.100000    3.210000    2.131575   
2    1998-12-01    3.290000    3.460000    3.220000    3.390000    2.251104   
3    1998-12-02    3.360000    3.440000    3.320000    3.390000    2.251104   
4    1998-12-03    3.440000    3.490000    3.370000    3.390000    2.251104   
...         ...         ...         ...         ...         ...         ...   
6144 2023-06-19  983.849976  986.000000  961.000000  965.650024  965.650024   
6145 2023-06-20  965.950012  977.000000  958.549988  974.849976  974.849976   
6146 2023-06-21  978.299988  978.299988  963.150024  966.000000  966.000000   
6147 2023-06-22  962.200012  973.450012  958.700012  966.599976  966.599976   
6148 2023-06-23  960.000000  965.500000  954.549988  958.400024  958.400024   

        Volume  
0        21000  
1       132000  
2       123500  
3        75500  
4       102000  
...        ...  
6144  11025846  
6145   7596593  
6146   7805855  
6147  10135883  
6148   6188008  

[6149 rows x 7 columns]

In [147]:
## how to read from a sql database

## a little later


## Structured Data

Metadata inspection

    rows, columns
    what are the column names
    memory?
    dtypes
    null values
    duplicates
    
    
    

Data inspection

    access columns, rows
    filter rows based on coditions
    calculations
        sum, mean, median, standard deviation
        
    sorting
    
    updating
    create new variables (KPIs)
    
    vizualisation
    
    joining
    
    aggregating / group by / pivot table
    
    
    transpose / pivoting
    
    renaming columns
    
    dropping duplicate / dropping null values
    
    missing value imputation
    
    altering data types
    
    
much more powerful

    
    
    
    

## Metadata Inspection

In [150]:
## rows and columns

data1.shape

(2500, 15)

In [151]:
data1.shape[0]  ## rows

2500

In [152]:
data1.shape[1]  ## columns

15

In [153]:
## dtypes

data1.dtypes

LoanID                              int64
Amount.Requested                  float64
Amount.Funded.By.Investors        float64
Interest.Rate                      object
Loan.Length                        object
Loan.Purpose                       object
Debt.To.Income.Ratio               object
State                              object
Home.Ownership                     object
Monthly.Income                    float64
FICO.Range                         object
Open.CREDIT.Lines                 float64
Revolving.CREDIT.Balance          float64
Inquiries.in.the.Last.6.Months    float64
Employment.Length                  object
dtype: object

In [154]:
## pandas assigns 'object' to string type variables

## object - python object

## `.head()`    `.tail()`

In [160]:
data1.head(5)

LoanID  Amount.Requested  Amount.Funded.By.Investors Interest.Rate  \
0       1           20000.0                     20000.0         8.90%   
1       2           19200.0                     19200.0        12.12%   
2       3           35000.0                     35000.0        21.98%   
3       4           10000.0                      9975.0         9.99%   
4       5           12000.0                     12000.0        11.71%   

  Loan.Length        Loan.Purpose Debt.To.Income.Ratio State Home.Ownership  \
0   36 months  debt_consolidation               14.90%    SC       MORTGAGE   
1   36 months  debt_consolidation               28.36%    TX       MORTGAGE   
2   60 months  debt_consolidation               23.81%    CA       MORTGAGE   
3   36 months  debt_consolidation               14.30%    KS       MORTGAGE   
4   36 months         credit_card               18.78%    NJ           RENT   

   Monthly.Income FICO.Range  Open.CREDIT.Lines  Revolving.CREDIT.Balance  \
0         6541.67    735-739               14.0                   14272.0   
1         4583.33    715-719               12.0                   11140.0   
2        11500.00    690-694               14.0                   21977.0   
3         3833.33    695-699               10.0                    9346.0   
4         3195.00    695-699               11.0                   14469.0   

   Inquiries.in.the.Last.6.Months Employment.Length  
0                             2.0          < 1 year  
1                             1.0           2 years  
2                             1.0           2 years  
3                             0.0           5 years  
4                             0.0           9 years

In [161]:
data1.tail()

LoanID  Amount.Requested  Amount.Funded.By.Investors Interest.Rate  \
2495    2496           30000.0                    29950.00        16.77%   
2496    2497           16000.0                    16000.00        14.09%   
2497    2498           10000.0                    10000.00        13.99%   
2498    2499            6000.0                     6000.00        12.42%   
2499    2500            9000.0                     5242.75        13.79%   

     Loan.Length        Loan.Purpose Debt.To.Income.Ratio State  \
2495   60 months  debt_consolidation               19.23%    NY   
2496   60 months    home_improvement               21.54%    MD   
2497   36 months  debt_consolidation                4.89%    PA   
2498   36 months      major_purchase               16.66%    NJ   
2499   36 months  debt_consolidation                6.76%    NY   

     Home.Ownership  Monthly.Income FICO.Range  Open.CREDIT.Lines  \
2495       MORTGAGE         9250.00    705-709               15.0   
2496            OWN         8903.25    740-744               18.0   
2497       MORTGAGE         2166.67    680-684                4.0   
2498           RENT         3500.00    675-679                8.0   
2499           RENT         3875.00    670-674                7.0   

      Revolving.CREDIT.Balance  Inquiries.in.the.Last.6.Months  \
2495                   45880.0                             1.0   
2496                   18898.0                             1.0   
2497                    4544.0                             0.0   
2498                    7753.0                             0.0   
2499                    7589.0                             0.0   

     Employment.Length  
2495           8 years  
2496         10+ years  
2497         10+ years  
2498           5 years  
2499         10+ years

In [162]:
data1.columns

Index(['LoanID', 'Amount.Requested', 'Amount.Funded.By.Investors',
       'Interest.Rate', 'Loan.Length', 'Loan.Purpose', 'Debt.To.Income.Ratio',
       'State', 'Home.Ownership', 'Monthly.Income', 'FICO.Range',
       'Open.CREDIT.Lines', 'Revolving.CREDIT.Balance',
       'Inquiries.in.the.Last.6.Months', 'Employment.Length'],
      dtype='object')

In [163]:
## to check the cardinality of the data

## .nunique()

In [164]:
data1.nunique()

LoanID                            2500
Amount.Requested                   380
Amount.Funded.By.Investors         710
Interest.Rate                      275
Loan.Length                          2
Loan.Purpose                        14
Debt.To.Income.Ratio              1669
State                               46
Home.Ownership                       5
Monthly.Income                     632
FICO.Range                          38
Open.CREDIT.Lines                   29
Revolving.CREDIT.Balance          2349
Inquiries.in.the.Last.6.Months      10
Employment.Length                   11
dtype: int64

## `.info()`

In [165]:
## entire report on metadata of your data

data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   LoanID                          2500 non-null   int64  
 1   Amount.Requested                2499 non-null   float64
 2   Amount.Funded.By.Investors      2499 non-null   float64
 3   Interest.Rate                   2498 non-null   object 
 4   Loan.Length                     2500 non-null   object 
 5   Loan.Purpose                    2500 non-null   object 
 6   Debt.To.Income.Ratio            2499 non-null   object 
 7   State                           2500 non-null   object 
 8   Home.Ownership                  2499 non-null   object 
 9   Monthly.Income                  2499 non-null   float64
 10  FICO.Range                      2498 non-null   object 
 11  Open.CREDIT.Lines               2497 non-null   float64
 12  Revolving.CREDIT.Balance        24

In [166]:
## Data Inspection

data1.head()

LoanID  Amount.Requested  Amount.Funded.By.Investors Interest.Rate  \
0       1           20000.0                     20000.0         8.90%   
1       2           19200.0                     19200.0        12.12%   
2       3           35000.0                     35000.0        21.98%   
3       4           10000.0                      9975.0         9.99%   
4       5           12000.0                     12000.0        11.71%   

  Loan.Length        Loan.Purpose Debt.To.Income.Ratio State Home.Ownership  \
0   36 months  debt_consolidation               14.90%    SC       MORTGAGE   
1   36 months  debt_consolidation               28.36%    TX       MORTGAGE   
2   60 months  debt_consolidation               23.81%    CA       MORTGAGE   
3   36 months  debt_consolidation               14.30%    KS       MORTGAGE   
4   36 months         credit_card               18.78%    NJ           RENT   

   Monthly.Income FICO.Range  Open.CREDIT.Lines  Revolving.CREDIT.Balance  \
0         6541.67    735-739               14.0                   14272.0   
1         4583.33    715-719               12.0                   11140.0   
2        11500.00    690-694               14.0                   21977.0   
3         3833.33    695-699               10.0                    9346.0   
4         3195.00    695-699               11.0                   14469.0   

   Inquiries.in.the.Last.6.Months Employment.Length  
0                             2.0          < 1 year  
1                             1.0           2 years  
2                             1.0           2 years  
3                             0.0           5 years  
4                             0.0           9 years

In [168]:
## numerical columns

data1.describe().T

count          mean           std      min  \
LoanID                          2500.0   1250.500000    721.832160     1.00   
Amount.Requested                2499.0  12405.462185   7802.933666  1000.00   
Amount.Funded.By.Investors      2499.0  12002.374186   7746.767348    -0.01   
Monthly.Income                  2499.0   5688.931321   3963.118185   588.50   
Open.CREDIT.Lines               2497.0     10.072887      4.507416     2.00   
Revolving.CREDIT.Balance        2497.0  15223.184622  18281.015258     0.00   
Inquiries.in.the.Last.6.Months  2497.0      0.906688      1.231149     0.00   

                                    25%      50%       75%       max  
LoanID                           625.75   1250.5   1875.25    2500.0  
Amount.Requested                6000.00  10000.0  17000.00   35000.0  
Amount.Funded.By.Investors      6000.00  10000.0  16000.00   35000.0  
Monthly.Income                  3500.00   5000.0   6800.00  102750.0  
Open.CREDIT.Lines                  7.00      9.0     13.00      38.0  
Revolving.CREDIT.Balance        5584.00  10948.0  18861.00  270800.0  
Inquiries.in.the.Last.6.Months     0.00      0.0      1.00       9.0

In [169]:
## count - non null value count

## mean - average

## central tendency 

## std - deviation from the mean




In [170]:
## 5 point summary

## q0 - min - 0 %ile
## q1  - 25%ile
## q2  - 50%ile  - median
## q3  - 75%ile
## max - 100%ile

In [173]:
data1.describe(include='object')

Interest.Rate Loan.Length        Loan.Purpose Debt.To.Income.Ratio  \
count           2498        2500                2500                 2499   
unique           275           2                  14                 1669   
top           12.12%   36 months  debt_consolidation                   0%   
freq             122        1952                1307                    8   

       State Home.Ownership FICO.Range Employment.Length  
count   2500           2499       2498              2423  
unique    46              5         38                11  
top       CA       MORTGAGE    670-674         10+ years  
freq     433           1147        171               653