## pip and PyPI

pip is the package manager for python. It connects to Python Package Index (PyPI) and downloads any package that you require.

## Numpy - Numerical python

great for scientific computation in python.

Moreover, many important packages are built on top of numpy. like `pandas`, `opencv`, `scikit-learn`

Applications of numpy

1. gives a base for storing large data sets
2. great for Linear Algebra and other scientific computation
3. is the base for many other important packages such as pandas, tensorflow, keras, openCV
4. Random number generation

In [2]:
import numpy as np

In [3]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\Vitta\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\vitta\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

Numpy provides to me another datastructure which is called the `ndarray`

## properties of `ndarray`

written in C

1. Homogeneous in nature
2. Allows broadcasting and vectorization
3. Provides efficicent mathematical operations

Things to look at

1. How to create
2. How to iterate
3. Important methods and attributes
4. How to make calculations

## creation

using the type conversion function `np.array()`

In [6]:
a1 = np.array([1, 2, 3, 4])
print(a1)

[1 2 3 4]


In [7]:
type(a1)

numpy.ndarray

## some important attributes to inspect an array

`.shape` `.size` `.dtype` `.nbytes` `.ndim`

In [8]:
a1.shape ## gives the shape of the array in the form of a tuple

(4,)

In [9]:
a1.ndim

1

In [10]:
a1.dtype

dtype('int32')

In [13]:
a2 = np.array([1, 2, 3, 4], dtype='int8')
print(a2)

[1 2 3 4]


In [14]:
a1.nbytes

16

In [15]:
a2.nbytes

4

In [16]:
a2.dtype

dtype('int8')

In [17]:
a3 = np.array(['a', 'b', 'c', 'd'])
print(a3)

['a' 'b' 'c' 'd']


In [18]:
type(a3)

numpy.ndarray

In [19]:
a3.dtype

dtype('<U1')

In [20]:
print(a3.size)
print(a3.ndim)
print(a3.shape)
print(a3.nbytes)

4
1
(4,)
16


In [21]:
a4 = np.array([1, 2, 'a', 1.5, 'b'])
print(a4)

['1' '2' 'a' '1.5' 'b']


In [22]:
a4.dtype

dtype('<U32')

In [23]:
## 2D array

a5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a5

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
a5.ndim

2

In [25]:
a5.shape

(2, 4)

In [26]:
a5.shape[0]

2

In [27]:
a5.shape[1]

4

In [38]:
a6 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [11, 12, 13, 14]],
              [[1, 2, 3, 4], [5, 6, 7, 8], [11, 12, 13, 14]]
              ])
a6

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [11, 12, 13, 14]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [11, 12, 13, 14]]])

In [39]:
a6.ndim

3

In [40]:
a6.shape

(2, 3, 4)

## Other important functions that help create arrays

`np.arange()` `np.linspace()`

In [43]:
## Q: create an array of integers starting from 0 till 10

a7 = np.arange(0, 11)
a7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
a8 = np.arange(0, 1.01, 0.01)  ## it works with float values as well. range() function didn't
a8

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [51]:
## Q: generate 100 linearly spaced numbers between 0 and 20

a9 = np.linspace(0, 20, 100)  ## in linspace, the end value is also included
a9

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

## generate random numbers

`np.random.random()`  `np.random.randint()`

In [4]:
np.random.random((100, 2))

array([[0.41554967, 0.7011935 ],
       [0.77437472, 0.07518223],
       [0.62503312, 0.7328282 ],
       [0.86020792, 0.94591536],
       [0.84044888, 0.68652195],
       [0.11341112, 0.56258364],
       [0.16678215, 0.30017786],
       [0.20275358, 0.19016264],
       [0.51908141, 0.62457223],
       [0.21144426, 0.56360184],
       [0.34251076, 0.18911549],
       [0.68722882, 0.1021145 ],
       [0.73088507, 0.64128508],
       [0.58794815, 0.16966847],
       [0.04015077, 0.56803639],
       [0.50334774, 0.74433354],
       [0.20075417, 0.01799558],
       [0.90008317, 0.19265827],
       [0.13260728, 0.00427211],
       [0.61805935, 0.56012234],
       [0.92098258, 0.27553796],
       [0.39732097, 0.7498418 ],
       [0.81012083, 0.37426395],
       [0.93345256, 0.92719905],
       [0.30917284, 0.94705889],
       [0.63057423, 0.94527284],
       [0.30711829, 0.28282019],
       [0.31071334, 0.90848022],
       [0.47973761, 0.00234947],
       [0.28267414, 0.71787823],
       [0.

In [5]:
## generate a 2d array of 10 by 10 and fill the array with random numbers between 0 and 1.

a9 = np.random.random((10, 10))
a9

array([[0.01368336, 0.11314762, 0.99689218, 0.53357223, 0.73570064,
        0.20670832, 0.84190716, 0.41328103, 0.78320538, 0.42500464],
       [0.49495777, 0.00283747, 0.3968945 , 0.36725753, 0.18076677,
        0.52474291, 0.73018734, 0.77528717, 0.42307315, 0.90057864],
       [0.8929631 , 0.71296811, 0.96277718, 0.91652032, 0.37699023,
        0.29175061, 0.29114173, 0.45781986, 0.0529834 , 0.09382295],
       [0.40215045, 0.87834398, 0.35507424, 0.02848635, 0.19451378,
        0.15638524, 0.45103998, 0.7144127 , 0.25276635, 0.56755359],
       [0.07212673, 0.09863474, 0.9211975 , 0.25942165, 0.24949674,
        0.01885492, 0.28315432, 0.36615678, 0.63560222, 0.81661013],
       [0.06778698, 0.45089816, 0.16910508, 0.03997388, 0.55254376,
        0.22721058, 0.5864713 , 0.1208749 , 0.98054795, 0.91207434],
       [0.15651175, 0.18647782, 0.62823497, 0.10475648, 0.61683818,
        0.82896349, 0.25741582, 0.67225711, 0.6039438 , 0.06545736],
       [0.87876036, 0.24437705, 0.8840068

In [119]:
np.random.randint(10, 100, 5)

array([84, 15, 37, 13, 47])

In [103]:
## Q: Generate 15 random numbers between 0 and 10

a9 = np.random.randint(0, 10, 15)
a9

array([3, 3, 8, 1, 4, 3, 8, 8, 8, 2, 9, 4, 5, 2, 8])

## `.reshape()`

In [105]:
a9

array([3, 3, 8, 1, 4, 3, 8, 8, 8, 2, 9, 4, 5, 2, 8])

In [106]:
a9.shape

(15,)

In [109]:
a9.reshape((5, 3))

array([[3, 3, 8],
       [1, 4, 3],
       [8, 8, 8],
       [2, 9, 4],
       [5, 2, 8]])

`np.zeros()` `np.ones()` `np.full()` `np.identity()`

In [6]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.zeros((10, 10,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],


In [7]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
np.full((10, 10), 'python')

array([['python', 'python', 'python', 'python', 'python', 'python',
        'python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python', 'python', 'python',
        'python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python', 'python', 'python',
        'python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python', 'python', 'python',
        'python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python', 'python', 'python',
        'python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python', 'python', 'python',
        'python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python', 'python', 'python',
        'python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python', 'python', 'python',
        'python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python', 'python', 'pytho

In [118]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Access elements out of an array

`[]`

In multidimensional arrays, indexes need to be separated by commas for each dimension.

In [130]:
a1

array([1, 2, 3, 4])

In [131]:
a1[0]

1

In [132]:
a1[-1]

4

In [134]:
## slicing

a1[:3]

array([1, 2, 3])

In [137]:
a10 = a9.reshape((5, 3))

In [138]:
a10

array([[3, 3, 8],
       [1, 4, 3],
       [8, 8, 8],
       [2, 9, 4],
       [5, 2, 8]])

In [139]:
a10[0, 0]

3

In [141]:
a10[0, :]

array([3, 3, 8])

In [142]:
a10[3, 1]

9

In [145]:
## fetch the first column

a10[: , 1]

array([3, 4, 8, 9, 2])

In [146]:
a10

array([[3, 3, 8],
       [1, 4, 3],
       [8, 8, 8],
       [2, 9, 4],
       [5, 2, 8]])

In [150]:
a10[1:3, 1:3]

array([[4, 3],
       [8, 8]])

In [152]:
a10[:, -1]

array([8, 3, 8, 4, 8])

In [154]:
a10[3:, :]

array([[2, 9, 4],
       [5, 2, 8]])

In [156]:
a10[2:, 1:]

array([[8, 8],
       [9, 4],
       [2, 8]])

## updating elements

In [157]:
a10

array([[3, 3, 8],
       [1, 4, 3],
       [8, 8, 8],
       [2, 9, 4],
       [5, 2, 8]])

In [159]:
a10[0, 0] = -1

In [160]:
a10

array([[-1,  3,  8],
       [ 1,  4,  3],
       [ 8,  8,  8],
       [ 2,  9,  4],
       [ 5,  2,  8]])

In [170]:
a10

array([[-1,  3,  8],
       [ 1,  4,  3],
       [-1,  0,  0],
       [ 2,  0,  0],
       [ 5,  2,  8]])

In [172]:
a10[2] = [-1, -2, -3]

In [173]:
a10

array([[-1,  3,  8],
       [ 1,  4,  3],
       [-1, -2, -3],
       [ 2,  0,  0],
       [ 5,  2,  8]])

In [164]:
a10[2] = -1 ## not possible for a list

In [165]:
a10

array([[-1,  3,  8],
       [ 1,  4,  3],
       [-1, -1, -1],
       [ 2,  9,  4],
       [ 5,  2,  8]])

In [166]:
a10

array([[-1,  3,  8],
       [ 1,  4,  3],
       [-1, -1, -1],
       [ 2,  9,  4],
       [ 5,  2,  8]])

In [168]:
a10[2:4, 1:] = 0

In [169]:
a10

array([[-1,  3,  8],
       [ 1,  4,  3],
       [-1,  0,  0],
       [ 2,  0,  0],
       [ 5,  2,  8]])

`.transpose()`, `.T`

In [177]:
print(a10)
a10 = a10.transpose() ## no permanent change
print(a10)

[[-1  3  8]
 [ 1  4  3]
 [-1 -2 -3]
 [ 2  0  0]
 [ 5  2  8]]
[[-1  1 -1  2  5]
 [ 3  4 -2  0  2]
 [ 8  3 -3  0  8]]


In [178]:
a10.T    ## no brackets required here

array([[-1,  3,  8],
       [ 1,  4,  3],
       [-1, -2, -3],
       [ 2,  0,  0],
       [ 5,  2,  8]])

## Making calculations on arrays

In [181]:
a10 + 10

array([[ 9, 11,  9, 12, 15],
       [13, 14,  8, 10, 12],
       [18, 13,  7, 10, 18]])

In [182]:
a10 ** 2

array([[ 1,  1,  1,  4, 25],
       [ 9, 16,  4,  0,  4],
       [64,  9,  9,  0, 64]], dtype=int32)

In [183]:
a10 // 10

array([[-1,  0, -1,  0,  0],
       [ 0,  0, -1,  0,  0],
       [ 0,  0, -1,  0,  0]], dtype=int32)

In [184]:
a10 * -1

array([[ 1, -1,  1, -2, -5],
       [-3, -4,  2,  0, -2],
       [-8, -3,  3,  0, -8]])

In [186]:
## Boolean indexing or filtering numpy arrays

In [188]:
a1[[True, True, False, False]]

array([1, 2])

In [191]:
a1[ a1 > 2 ]

array([3, 4])

In [193]:
a1[[True, True, False, True]]

array([1, 2, 4])

In [195]:
a1[ a1 > 2 ]

array([3, 4])

In [197]:
a10[ a10 > 4 ]

array([5, 8, 8])

In [204]:
a10[ (a10 > 4) & (a10 < 8)]

array([5])

In [205]:
a11 = np.random.randint(5, 20, (5, 4))
a11

array([[12,  8, 18, 10],
       [12, 10, 17,  8],
       [17,  6, 10,  8],
       [11, 13, 14, 18],
       [ 8,  6, 16, 10]])

In [208]:
## Q: get all the elemnts which are not 6

a11[~(a11 == 6)]

array([12,  8, 18, 10, 12, 10, 17,  8, 17, 10,  8, 11, 13, 14, 18,  8, 16,
       10])

`np.hstack()`

`np.vstack()`

In [209]:
np.hstack?

In [210]:
a10

array([[-1,  1, -1,  2,  5],
       [ 3,  4, -2,  0,  2],
       [ 8,  3, -3,  0,  8]])

In [215]:
a12 = np.random.randint(5, 10, (3, 3))
a12

array([[5, 6, 9],
       [9, 8, 7],
       [7, 5, 5]])

In [216]:
np.hstack((a10, a12)) ## horizontal stacking

array([[-1,  1, -1,  2,  5,  5,  6,  9],
       [ 3,  4, -2,  0,  2,  9,  8,  7],
       [ 8,  3, -3,  0,  8,  7,  5,  5]])

In [217]:
a10

array([[-1,  1, -1,  2,  5],
       [ 3,  4, -2,  0,  2],
       [ 8,  3, -3,  0,  8]])

In [218]:
a13 = np.random.randint(5, 10, (5, 5))
a13

array([[6, 8, 5, 5, 6],
       [7, 7, 7, 7, 7],
       [6, 6, 7, 5, 9],
       [5, 5, 7, 7, 7],
       [5, 6, 5, 7, 6]])

In [220]:
np.vstack((a13, a10))

array([[ 6,  8,  5,  5,  6],
       [ 7,  7,  7,  7,  7],
       [ 6,  6,  7,  5,  9],
       [ 5,  5,  7,  7,  7],
       [ 5,  6,  5,  7,  6],
       [-1,  1, -1,  2,  5],
       [ 3,  4, -2,  0,  2],
       [ 8,  3, -3,  0,  8]])